### ISSUE TITLE
Bill관련 몇가지 API더 부탁드려도 될까요?

### ISSUE THREAD

**Issue by hunkim** [teampopong/popong-api#9]
우선 bill과 관련하여

1.  list/?term&page: 리스트로 제목과 billid정도만 가져올수 있으면 좋을것 같습니다. 많을 경우 페이지로 나누어서 볼수 있으면 좋겠습니다.

2.  bill/billid: bill id 로 해당하는 빌을 가져올수 있으면 좋겠습니다. 여기에 요약과 공동발의한 분들의 리스트가 나와주면 좋을것 같습니다.

좋은 API감사합니다.

**Comment by e9t** [comment]
안녕하세요 :)

말씀하신 요청사항을 아래의 5개의 task로 나눠볼 수 있을 것 같습니다: 

1. [ ] 결과 요청시 항목 필터링 기능 추가 (ex: 19대 의안만 반환)
1. [ ] 결과 반환시 변수 필터링 기능 추가 (ex: 의안의 title, id만 반환)
1. [x] 결과 반환시 페이지를 나누고 페이지 별로 접근 가능하게 함
1. [x] id 입력시 해당 bill 반환
1. [x] bill 반환시 공동발의 명단 반환
